services:
  - type: web
    name: sistema_juridico
    runtime: python
        buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: "gunicorn sistema_juridico.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: 'django-insecure-p@ckyik0c6$$#ghd4+f4omksoc)cs$)a_&i*_5m5!h-21a&4wx'
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "1"  